// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uemoqhiqqdpjfnyqfmej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVlbW9xaGlxcWRwamZueXFmbWVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyOTg3NDgsImV4cCI6MjA3MTg3NDc0OH0.GHZaElrilhvPRxNQBVWMPfpkGjHid2iCSk2SQngWj8E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});